name: Bug Report
description: Report a bug within ATIdentityTools.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report! Please note that this form is for bugs only!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Summarize the bug in one or two sentences.
      placeholder: "Resolving an invalid handle takes longer than the amount of time it takes to timeout."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Describe how you were able to get the bug.
      placeholder: |
        1. Create an instance of `HandlerResolver`.
        2. Use `resolve()` and input a handle that doesn't exist.
        3. `print` out the result.
        4. Contain the code in a `do-catch` block.
    validations:
      required: true
  - type: textarea
    id: expected-results
    attributes:
      label: Expected Results
      description: What were you expecting to happen?
      placeholder: "The handle should throw an error, or it should be long enough to time itself out."
    validations:
      required: true
  - type: textarea
    id: actual-results
    attributes:
      label: Actual Results
      description: What actually happened?
      placeholder: "No error is thrown, then 30 seconds later, the error \"The request has timed out.\" appears."
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: What operating systems did you experience this bug?
      multiple: true
      options:
        - macOS
        - iOS/iPadOS
        - tvOS
        - visionOS
        - watchOS
        - Linux
        - Docker
        - Other
    validations:
      required: true
  - type: textarea
    id: os-version
    attributes:
      label: Operating System Version
      description: For each operating system, give us the version numbers. For "Linux," state what distro you're using. For "Other," state what operating system you're using. For "Docker," state what version and Linux distro you're using.
      placeholder: |
        macOS Sonoma 14.4
        Linux (Ubuntu 22.04 LTS)
    validations:
      required: true
  - type: input
    id: atidentitytools-version
    attributes:
      label: ATIdentityTools Version
      description: State what version of ATIdentityTools you're using.
      placeholder: "0.1.0"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Add any other context, screenshots, or videos about the bug here. Please note: if the JSON response is too large, please attach it as a .json file in here."
      placeholder: |
        Below is the code that can be copied and pasted to test:
        ```swift
        do {
          let handleResolver = HandleResolver()
          let handleResult = try await handleResolver.resolve(handle: "apple.ca")
          if let did = handleResult {
            print("Handle resolved to: \(did)")
          } else {
            print("No DID found for handle.")
          }
        } catch {
          print(error)
        }
        ```
